kind: pipeline
name: default

steps:
- name: build
  image: golang:alpine
  volumes:
    - name: govendor
      path: /go/src
  commands:
    - GOOS=linux GOARCH=adm64 go build -o release/drone-test .
#  - export GO111MODULE=off
#  - pwd
#  - ls -la
#  - mkdir -p /go/src/github.com/lurise/drone-test
#  - cp -r /drone/src/* /go/src/github.com/lurise/drone-test
#  - cd /go/src/github.com/lurise/drone-test
#  - GOOS=linux GOARCH=amd64 go build --ldflags "-extldflags -static" -o /drone/src/release/drone-test .

- name: docker
  image: plugins/docker
  settings:
   username: lurise
   password:
    from_secret: dockerPwd
   repo: lurise/drone-test

- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - 49.235.35.141
    username: root
    password:
      from_secret: sshPwd
    command_timeout: 2m
    script:
    - docker rm drone-test -f
    - docker rmi lurise/drone-test
    - docker run -p 8080:8080 --name drone-test lurise/drone-test

volumes:
  - name: govendor
    host:
      path: /src